### PR TITLE
Updating to Ecto 3.0

### LINKED ISSUE #58: Updating to ecto 3.0
I think this is a pretty low effort based on [this](http://blog.plataformatec.com.br/2018/10/a-sneak-peek-at-ecto-3-0-breaking-changes/). Mostly updating tests?

I'm getting `Failed to use "ecto" (version 3.0.4) because filtrex (versions 0.4.1 and 0.4.2) requires ~> 2.1`

### PR DESCRIPTION
**Pull request by JohnKacz**
Should close #58. 

I'm getting `[error] an exception was raised logging %DBConnection.LogEntry{...}: ** (ArgumentError) argument error` for each test, but all tests pass. Not exactly sure what's causing the logging error but happy to provide more info.

### CODE REVIEW

**Comment by JohnKacz** [comment]
Might be good to also cut a new release once these are merged?

**Comment by rcdilorenzo** [comment]
@JohnKacz It looks good as far as it goes. I'll try to pull it down when I can and take a look at the exception you mentioned. Do you have more details?

Oh, and thanks so much for the PR. 👍

**Comment by JohnKacz** [comment]
So when I run the tests locally there are 18 times that it seems `DBConnection.log/5` gets called and errors with `[error] an exception was raised logging %DBConnection.LogEntry{...[LONG_LIST_OF_PARAMS]...}: ** (ArgumentError) argument error`

The first time is from `test/test_helper.exs:20: (file)`
The next 7 are from `(ecto) lib/ecto/repo/schema.ex:647: Ecto.Repo.Schema.apply/4`
10 of the times are from 
````
test/filtrex_test.exs:62: FiltrexTest."test creating an 'all' ecto filter query"/1
test/filtrex_test.exs:175: FiltrexTest."test .query returns no results if allow_empty: false"/1
test/filtrex_test.exs:118: FiltrexTest."test creating a filter with a datetime expression"/1
test/filtrex_test.exs:154: FiltrexTest."test parsing string keys"/1
test/filtrex_test.exs:108: FiltrexTest."test creating filter with numbers in the conditions"/1
test/filtrex_test.exs:82: FiltrexTest."test creating a 'none' ecto filter query"/1
test/filtrex_test.exs:167: FiltrexTest."test pipelining to query"/1
test/filtrex_test.exs:72: FiltrexTest."test creating an 'any' ecto filter query"/1
test/filtrex_test.exs:141: FiltrexTest."test parsing empty parameters"/1
test/filtrex_test.exs:97: FiltrexTest."test creating subfilters"/1
````


One example of the full trace is
````
09:31:58.361 [error] an exception was raised logging %DBConnection.LogEntry{call: :prepare_execute, connection_time: 704000, decode_time: 5000, params: [], pool_time: 618000, query: %Postgrex.Query{cache: :reference, columns: nil, name: "ecto_17026", param_formats: nil, param_oids: nil, param_types: nil, ref: nil, result_formats: nil, result_oids: nil, result_types: nil, statement: "SELECT count(s0.\"id\") FROM \"sample_models\" AS s0", types: nil}, result: {:ok, %Postgrex.Query{cache: :reference, columns: ["count"], name: "ecto_17026", param_formats: [], param_oids: [], param_types: [], ref: #Reference<0.3233704320.4095213569.106610>, result_formats: [:binary], result_oids: [20], result_types: [Postgrex.Extensions.Int8], statement: "SELECT count(s0.\"id\") FROM \"sample_models\" AS s0", types: {Postgrex.DefaultTypes, #Reference<0.3233704320.4095344641.105576>}}, %Postgrex.Result{columns: ["count"], command: :select, connection_id: 64206, messages: [], num_rows: 1, rows: ['\a']}}}: ** (ArgumentError) argument error
    (stdlib) :ets.lookup(Telemetry.HandlerTable, [:filtrex, :repo, :query])
    lib/telemetry/handler_table.ex:59: Telemetry.HandlerTable.list_for_event/1
    lib/telemetry.ex:76: Telemetry.execute/3
    lib/ecto/adapters/sql.ex:770: Ecto.Adapters.SQL.log/4
    (db_connection) lib/db_connection.ex:1311: DBConnection.log/5
    lib/ecto/adapters/sql.ex:545: Ecto.Adapters.SQL.execute!/4
    lib/ecto/adapters/sql.ex:537: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/queryable.ex:74: Ecto.Repo.Queryable.one!/3
    test/filtrex_test.exs:210: FiltrexTest.assert_count/3
    test/filtrex_test.exs:141: FiltrexTest."test parsing empty parameters"/1
    (ex_unit) lib/ex_unit/runner.ex:312: ExUnit.Runner.exec_test/1
    (stdlib) timer.erl:166: :timer.tc/1
    (ex_unit) lib/ex_unit/runner.ex:251: anonymous fn/4 in ExUnit.Runner.spawn_test/3
````

Hope that helps.

**Comment by rcdilorenzo** [comment]
@JohnKacz I haven't forgotten you. I pulled the changes down yesterday on a flight but didn't have internet access to do some research. I'm hoping to investigate this in the next week or so.

**Comment by JohnKacz** [comment]
Hey @rcdilorenzo just came back to this to check on it. I did a quick search and found the [solution](https://elixirforum.com/t/telemetry-logging-error/18609/4)

`:logger` needed to be listed in the new `:extra_applications`

I also updated the migration to use `:naive_datetime`

All tests pass with no warnings or logging errors now.

**Comment by rcdilorenzo** [comment]
Thanks so much. 🎉  I'll try to pull it down and run it. Then, I'll send out a release.

**Pull request merged**
